ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/beats/metricbeat:${ELK_VERSION}

# Auto-Create Kibana Metricbeat Dashboard Tables 
#RUN /usr/share/metricbeat/metricbeat setup --dashboards
